package com.habitflowai.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class ReassessmentQuestion(
    val id: String,
    val question: String,
    val options: List<String>
)

data class DriftReassessmentUiState(
    val questions: List<ReassessmentQuestion> = emptyList(),
    val answers: Map<String, String> = emptyMap(),
    val isSubmitting: Boolean = false,
    val isSuccess: Boolean = false,
    val isLoading: Boolean = false
)

@HiltViewModel
class DriftViewModel @Inject constructor() : ViewModel() {

    private val _uiState = MutableStateFlow(DriftReassessmentUiState())
    val uiState: StateFlow<DriftReassessmentUiState> = _uiState.asStateFlow()

    init {
        loadQuestions()
    }

    private fun loadQuestions() {
        _uiState.value = _uiState.value.copy(isLoading = true)
        // Mocking questions generated by backend
        val mockQuestions = listOf(
            ReassessmentQuestion(
                "1",
                "You've been skipping your morning meditation lately. Is the 6 AM time still working for you?",
                listOf("Yes, I just need more discipline", "No, it's too early", "I've lost interest")
            ),
            ReassessmentQuestion(
                "2",
                "We noticed you're more active with social habits. Would you like to shift your focus more toward community goals?",
                listOf("Absolutely", "Maybe a little", "No, keep my current plan")
            )
        )
        _uiState.value = _uiState.value.copy(questions = mockQuestions, isLoading = false)
    }

    fun onAnswerSelected(questionId: String, answer: String) {
        val newAnswers = _uiState.value.answers.toMutableMap().apply {
            put(questionId, answer)
        }
        _uiState.value = _uiState.value.copy(answers = newAnswers)
    }

    fun submitReassessment() {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isSubmitting = true)
            // Simulate API call
            kotlinx.coroutines.delay(1500)
            _uiState.value = _uiState.value.copy(isSubmitting = false, isSuccess = true)
        }
    }
}
